<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_KAMPAGNENDEFINITION</name>
   <tag></tag>
   <elementGuidId>98656f15-7578-4c3b-a408-360b8cd89ccb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@type = 'button' and (text() = ' KAMPAGNENDEFINITION ' or . = ' KAMPAGNENDEFINITION ')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>workflowselection d-inline-flex align-items-center</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> KAMPAGNENDEFINITION </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/routercomponent[1]/initcomponent[@class=&quot;ng-star-inserted&quot;]/v7-overlay-panel-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;v7-panel v7-overlay-panel h-100&quot;]/div[@class=&quot;v7-panel h-100&quot;]/v7-center-panel-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;v7-panel v7-center-panel no-gutters row justify-content-start h-100&quot;]/div[@class=&quot;col-auto no-gutters&quot;]/v7-top-bottom-panel-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;v7-top-bottom-panel h-100&quot;]/div[@class=&quot;row no-gutters&quot;]/v7-flow-panel-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;v7-flow-panel no-gutters row hidden-container&quot;]/v7-left-right-panel-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;v7-panel v7-left-right-panel no-gutters row justify-content-start flex-nowrap v7-startpage&quot;]/div[@class=&quot;col no-gutters&quot;]/v7-workflow-select-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;workflowselection-container d-flex flex-wrap flex-column align-content-start&quot;]/div[@class=&quot;d-inline-flex ng-star-inserted&quot;]/div[@class=&quot;workflow-category-group ng-star-inserted&quot;]/button[@class=&quot;workflowselection d-inline-flex align-items-center&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SELEKTIEREN'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Workflows'])[1]/following::button[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kampagne erstellen'])[1]/preceding::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
   </webElementXpaths>
</WebElementEntity>
