<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Kunden</name>
   <tag></tag>
   <elementGuidId>400717e2-bba4-470c-a767-625fe3c2a1b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#folder-buttons > div > v7-flow-panel-component > div > v7-folder-button-component:nth-child(1) > div > button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ng-star-inserted:nth-child(1) > .v7-button > .btn-folder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='folder-buttons']/div/v7-flow-panel-component/div/v7-folder-button-component/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-md btn-folder cdk-focused cdk-mouse-focused</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kunden</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;folder-buttons&quot;)/div[@class=&quot;panel-body&quot;]/v7-flow-panel-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;v7-flow-panel no-gutters col-auto&quot;]/v7-folder-button-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;v7-button&quot;]/button[@class=&quot;btn btn-md btn-folder cdk-focused cdk-mouse-focused&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#folder-buttons > div > v7-flow-panel-component > div > v7-folder-button-component:nth-child(1) > div > button</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[10]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='folder-buttons']/div/v7-flow-panel-component/div/v7-folder-button-component/div/button</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategorien'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suchwort eingeben'])[1]/following::button[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verträge'])[1]/preceding::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//v7-folder-button-component/div/button</value>
   </webElementXpaths>
</WebElementEntity>
