<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Name</name>
   <tag></tag>
   <elementGuidId>ab58e271-5492-4439-94e4-0f8ecb7c6188</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::div[32]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-form-field-infix</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Name</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/routercomponent[1]/initcomponent[@class=&quot;ng-star-inserted&quot;]/v7-overlay-panel-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;v7-panel h-100&quot;]/div[@class=&quot;v7-panel h-100&quot;]/v7-center-panel-component[@class=&quot;v7-panel v7-center-panel no-gutters row justify-content-start h-100 ng-star-inserted&quot;]/div[@class=&quot;col-auto no-gutters&quot;]/v7-top-bottom-panel-component[@class=&quot;v7-campaign-management-definition ng-star-inserted&quot;]/div[@class=&quot;row no-gutters&quot;]/v7-top-bottom-panel-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row no-gutters&quot;]/v7-collapsible-left-right-panel-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;v7-panel v7-left-right-panel no-gutters row justify-content-start v7-campaign-management-measurement-page&quot;]/div[@class=&quot;col no-gutters&quot;]/v7-dynamic-form-campaign-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;v7-form default-content-size&quot;]/form[@class=&quot;ng-pristine ng-valid ng-touched&quot;]/v7-dynamic-form-group-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;v7-form-group ng-pristine ng-valid ng-touched&quot;]/v7-dynamic-form-group-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;v7-form-group v7-form-shadow ng-pristine ng-valid ng-touched&quot;]/v7-dynamic-form-group-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;v7-form-group ng-pristine ng-valid ng-touched&quot;]/v7-dynamic-form-array-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;v7-form-array&quot;]/v7-dynamic-form-group-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;v7-form-group ng-pristine ng-valid ng-touched&quot;]/v7-flow-panel-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;v7-flow-panel no-gutters row&quot;]/v7-dynamic-form-control-autocomplete-component[@class=&quot;v7-autocomplete-custom ng-star-inserted&quot;]/div[1]/mat-form-field[@class=&quot;mat-form-field ng-tns-c2-98 mat-primary mat-form-field-type-mat-input mat-form-field-appearance-outline mat-form-field-can-float mat-form-field-has-label ng-pristine ng-valid mat-form-field-should-float ng-touched mat-focused&quot;]/div[@class=&quot;mat-form-field-wrapper&quot;]/div[@class=&quot;mat-form-field-flex&quot;]/div[@class=&quot;mat-form-field-infix&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::div[32]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Messung'])[2]/following::div[33]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//v7-dynamic-form-control-autocomplete-component/div/mat-form-field/div/div/div[3]</value>
   </webElementXpaths>
</WebElementEntity>
