<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg (1)</name>
   <tag></tag>
   <elementGuidId>72e5ce06-caa9-47ef-9b6e-c3e6a72f7870</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>body > routercomponent > initcomponent > v7-overlay-panel-component > div > div.overlay-background > div > v7-top-bottom-panel-component > div:nth-child(1) > v7-collapsible-left-right-panel-component > div > div.col-auto.no-gutters > div > div > div:nth-child(1) > v7-folder-panel-component > div > div.panel-navigation > div > button.btn.btn-back > mat-icon > svg</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>body > routercomponent > initcomponent > v7-overlay-panel-component > div > div.overlay-background > div > v7-top-bottom-panel-component > div:nth-child(1) > v7-collapsible-left-right-panel-component > div > div.col-auto.no-gutters > div > div > div:nth-child(1) > v7-folder-panel-component > div > div.panel-navigation > div > button.btn.btn-back > mat-icon > svg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/routercomponent/initcomponent/v7-overlay-panel-component/div/div[2]/div/v7-top-bottom-panel-component/div[1]/v7-collapsible-left-right-panel-component/div/div[1]/div/div/div[1]/v7-folder-panel-component/div/div[3]/div/button[1]/mat-icon/svg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>preserveAspectRatio</name>
      <type>Main</type>
      <value>xMidYMid meet</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/routercomponent[1]/initcomponent[@class=&quot;ng-star-inserted&quot;]/v7-overlay-panel-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;v7-panel h-100&quot;]/div[@class=&quot;overlay-background&quot;]/div[@class=&quot;overlay-content&quot;]/v7-top-bottom-panel-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row no-gutters&quot;]/v7-collapsible-left-right-panel-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;v7-panel v7-left-right-panel no-gutters row justify-content-start panel-content-center&quot;]/div[@class=&quot;col-auto no-gutters&quot;]/div[@class=&quot;v7-collapse-to-left&quot;]/div[@class=&quot;d-flex flex-row&quot;]/div[1]/v7-folder-panel-component[@class=&quot;panel-edge overlay-sidebar-height ng-star-inserted&quot;]/div[@class=&quot;v7-button&quot;]/div[@class=&quot;panel-navigation&quot;]/div[@class=&quot;panel-nav&quot;]/button[@class=&quot;btn btn-back&quot;]/mat-icon[@class=&quot;mat-icon notranslate mat-icon-no-color&quot;]/svg[1]</value>
   </webElementProperties>
</WebElementEntity>
